# Generated by Django 2.0 on 2019-11-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='poster',
            field=models.ImageField(blank=True, help_text='Please Upload an Image with 16:9 Resolution', null=True, upload_to='posters/'),
        ),
    ]
